name: build-image

description: Build image

inputs:
  tag:
    type: string
    required: true
    description: Image tag
  arch:
    type: string
    required: true
    description: Image arch
  repo:
    type: string
    required: true
    description: Image repository
  push:
    type: string
    required: true
    default: never
    description: Push image to ghcr.io

runs:
  using: composite
  steps:

    - name: Setup runner environment
      uses: ./.github/actions/setup-runner-env

    - name: Install devcontainers CLI
      uses: ./.github/actions/install-devcontainers-cli

    - if: inputs.push == 'always'
      name: Login to ghcr.io
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}

    - name: Build ghcr.io/${{ inputs.repo }}:${{ inputs.tag }}-${{ inputs.arch }}
      uses: devcontainers/ci@v0.3
      env:
        NODE_NO_WARNINGS: 1
      with:
        push: ${{ inputs.push }}
        skipContainerUserIdUpdate: true
        subFolder: image
        imageTag: ${{ inputs.tag }}-${{ inputs.arch }}
        imageName: ghcr.io/${{ inputs.repo }}
        cacheFrom: ghcr.io/${{ inputs.repo }}:${{ inputs.tag }}
        # Set platform to an empty string when using self-hosted runners so
        # devcontainers/ci doesn't try to use skopeo (ubuntu 20.10+ only)
        platform: ${{ contains(runner.name, 'nvidia') != true && format('linux/{0}', inputs.arch) || '' }}
