name: free-disk-space

description: Free up disk space on the GitHub-hosted runners

inputs:
  tool_cache:
    type: string
    required: true
    description: Runner tool_cache

runs:
  using: composite
  steps:
    - name: Free up disk space
      shell: bash
      run: |
          set -x;
          df -h;
          docker images;
          sudo swapoff -a;
          sudo rm -f /swapfile /mnt/swapfile;
          sudo apt clean;
          sudo rm -rf /opt/az;
          sudo rm -rf /opt/ghc;
          sudo rm -rf /opt/google;
          sudo rm -rf /opt/microsoft;
          sudo rm -rf /usr/lib/mono;
          sudo rm -rf /usr/local/julia*;
          sudo rm -rf /usr/local/.ghcup;
          sudo rm -rf /usr/share/swift;
          sudo rm -rf /usr/share/dotnet;
          sudo rm -rf /usr/share/kotlinc;
          sudo rm -rf /usr/share/az_9.0.1;
          sudo rm -rf /usr/share/miniconda;
          sudo rm -rf /usr/share/gradle-7.6;
          sudo rm -rf /usr/local/share/boost;
          sudo rm -rf /usr/local/lib/android;
          sudo rm -rf /usr/local/share/chromium;
          sudo rm -rf /usr/local/share/powershell;
          sudo rm -rf /home/linuxbrew/.linuxbrew;
          sudo rm -rf ${{ inputs.tool_cache }}/go;
          sudo rm -rf ${{ inputs.tool_cache }}/Ruby;
          sudo rm -rf ${{ inputs.tool_cache }}/PyPy;
          sudo rm -rf ${{ inputs.tool_cache }}/CodeQL;
          sudo rm -rf ${{ inputs.tool_cache }}/Python;
          docker rmi $(docker image ls -aq) || true;
          docker images;
          df -h;
