name: install-devcontainers-cli

description: Install devcontainers CLI

runs:
  using: composite
  steps:

    - name: Setup Node.js
      if: contains(runner.name, github.repository_owner) == true
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install devcontainers CLI
      shell: bash
      run: |
        sudo apt update;
        sudo apt install -y --no-install-recommends build-essential;
        npm install -g @devcontainers/cli;
