name: Build and push devcontainer images

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
      tag:
        type: string
        required: true
      features:
        type: string
        required: true

jobs:

  build-and-upload:
    name: Build and upload
    runs-on: ${{ fromJSON(github.repository != 'NVIDIA/cccl_devcontainers' && '"ubuntu-latest"' || format('{{"labels":["self-hosted", "linux", "{0}", "cpu4"]}}', matrix.arch)) }}
    permissions:
      packages: read
    outputs:
      tag: ${{ steps.json.outputs.tag }}
      repo: ${{ steps.build.outputs.repo }}
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - id: json
        name: Write .devcontainer.json
        uses: ./.github/actions/devcontainer-json
        with:
          os : "${{ inputs.os }}"
          features: "${{ inputs.features }}"

      - id: build
        name: Build ${{ steps.json.outputs.tag }}-${{ matrix.arch }}
        uses: ./.github/actions/build-image
        with:
          arch: "${{ matrix.arch }}"
          tag: "${{ steps.json.outputs.tag }}"
          repo: "${{ format('{0}/cccl/devcontainers', github.repository_owner) }}"

      - name: Upload ${{ steps.json.outputs.tag }}-${{ matrix.arch }}
        uses: actions/upload-artifact@v3
        with:
          retention-days: 1
          name: ${{ steps.json.outputs.tag }}
          path: ${{ runner.temp }}/${{ matrix.arch }}.tar

  push-multiarch-manifest:
    name: Push multiarch manifest
    needs: build-and-upload
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Download ${{ needs.build-and-upload.outputs.tag }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build-and-upload.outputs.tag }}
          path: ${{ runner.temp }}

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Push multiarch manifest to ghcr.io
        shell: bash --noprofile --norc -x -eo pipefail {0}
        env:
          tag: "${{ needs.build-and-upload.outputs.tag }}"
        run: |

          find "${{ runner.temp }}/" -type f -name '*.tar';

          name="ghcr.io/${{ needs.build-and-upload.outputs.repo }}:${tag}";

          docker manifest rm ${name} || true;

          # Load and push the linux/amd64 image
          amd64_hash="$(docker load --input "${{ runner.temp }}/amd64.tar" | tail -n1 | cut -d':' -f3)";
          docker image tag ${amd64_hash} ${name};
          amd64_hash="$(docker push ${name} | tail -n1 | cut -d' ' -f3)";

          # Load and push the linux/arm64 image
          arm64_hash="$(docker load --input "${{ runner.temp }}/arm64.tar" | tail -n1 | cut -d':' -f3)";
          docker image tag ${arm64_hash} ${name};
          arm64_hash="$(docker push ${name} | tail -n1 | cut -d' ' -f3)";

          # Create and push the multiarch manifest
          docker buildx imagetools create --tag ${name} ${amd64_hash} ${arm64_hash};
