name: Download devcontainer image package sources

on:
  workflow_call:
    inputs:
      matrix:
        type: string
        required: true
      repo:
        type: string
        required: true
        description: Image repository

jobs:

  download-sources:
    name: Download apt sources
    runs-on: ${{ fromJSON(github.repository != 'NVIDIA/cccl_devcontainers' && '"ubuntu-latest"' || format('{{"labels":["self-hosted", "linux", "{0}", "cpu4"]}}', matrix.arch)) }}
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
