name: PR

concurrency:
  group: release-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  image-matrix:
    name: Determine image matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - id: matrix
        name: Determine image matrix
        uses: ./.github/actions/image-matrix

  push-images:
    if: needs.image-matrix.outputs.matrix != '{"include":[]}'
    name: ${{ matrix.tag }}-${{ matrix.os }}
    needs: image-matrix
    secrets: inherit
    uses: ./.github/workflows/build-and-push-image.yml
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.image-matrix.outputs.matrix) }}
    with:
      os : "${{ matrix.os }}"
      tag: "${{ matrix.tag }}"
      features: "${{ matrix.features }}"
